### ISSUE TITLE
Released version 2.0-RC2 bad link

### ISSUE THREAD

**Issue by bassmartin** [grails-plugins/grails-spring-security-appinfo#1]
The menu link to "Filter Chains" is wrong in the released version. It targets "/filterChains" but the action name is "/filterChain".

I can see Burt fixed it during his last cleanup.

We need a new release with this fix please.

Thanks.

**Comment by burtbeckwith** [comment]
I'll do another release, but until then you can copy the plugin's controller to your app and make the fix there since Grails lets you override artifacts if they're in the same relative location/package.

**Comment by bassmartin** [comment]
Thank you Burt!

**Comment by burtbeckwith** [comment]
Fixed in 2.0.0 and 3.0.0.M1
